### ISSUE TITLE
Config.json isn't created on new machines

### ISSUE THREAD

**Issue by vituskh** [andrewc2/LHWB-Bot#21]
When running, I get the error `Error: Cannot find module './config.json'`

**Comment by vituskh** [comment]
I realize there is an example file, but maybe it should be written in README, or it should just be renamed to config.json and then the gitignore will prevent changes to it

**Comment by andrewc2** [comment]
General practice is to provide an example file for configs as it prevents accidental leaks of tokens and such. As a result I don't have any interest in renaming the configs. I will however add a mention to the readme.
